### PR TITLE
Wrap UNIF subroutine in SSRFPACK

### PR DESCRIPTION
**Pull request by brmather**
In relation to #54

### CODE REVIEW

**Comment by lmoresi** [comment]
Is the travis check a random error - I don't see a specific error that explains why the build failed. If we can fix this and add the interface for tension factors into the standard interpolation then we ought to build a new release.

**Comment by brmather** [comment]
Travis errors out because it can't push the documentation for whatever reason. It's fine now.

The unstructured interpolation functions are crippled in our spherical implementation (actually they were inherited from some accelerated f90 version we wrapped). Tensioned splines are omitted. Before making a new release it would be worth restructuring the interpolation methods to just use `intrc0` and `intrc1` methods in `SSRFPACK` for linear and cubic interpolation.

**Comment by brmather** [comment]
Also, we need a unit test for tensioned splines!

**Comment by brmather** [comment]
The Cartesian module is up to snuff with all the spline tension doohickey, and the unit tests are up to date. I think we are ready to merge this PR.

1. merge `dev <- unif`
2. merge `master <- dev`
3. version 1.1 release

**Pull request merged**
