### PR TITLE
Use meson to build stripy

### PR DESCRIPTION
**Pull request by brmather**
`numpy.distutils` has been deprecated in Python 3.12, so we must move to meson.

The `meson.build` file contains details on the source files to compile. I've updated `pyproject.toml` to use meson as the build backend.

### CODE REVIEW

**Comment by brmather** [comment]
Currently, this successfully builds the fortran modules (_tripack, _stripack, _srfpack, _ssrfpack) but doesn't actually build stripy...

**Comment by brmather** [comment]
Getting some green ticks now...

**Comment by brmather** [comment]
Finally getting green ticks...

@lmoresi - are you fine with me to squash and merge?

**Comment by lmoresi** [comment]
That was quite the adventure - happy to see this merged and then onto the next repo !!




Sent from my iPhone

On 5 Dec 2023, at 16:53, Ben Mather ***@***.***> wrote:

﻿

Finally getting green ticks...

@lmoresi<https://github.com/lmoresi> - are you fine with me to squash and merge?

**Pull request merged**
